export const grievanceCategories = [
  {
    id: 'academics',
    name: 'Academics',
    color: '#8B5CF6',
    icon: 'book',
    subcategories: [
      'Faculty behavior or teaching issues',
      'Attendance discrepancies',
      'Internal marks / lab marks disputes',
      'Syllabus coverage or delay',
      'Exam schedule or revaluation issues',
      'Subject change or elective confusion',
      'Class timing clash',
    ],
  },
  {
    id: 'examination',
    name: 'Examination',
    color: '#EC4899',
    icon: 'award',
    subcategories: [
      'Result not published / delayed',
      'Wrong grade / CGPA calculation',
      'Answer sheet not evaluated',
      'Hall ticket issues',
      'Backlog registration problems',
      'Exam form submission errors',
      'Malpractice allegation disputes',
    ],
  },
  {
    id: 'administrative',
    name: 'Administrative',
    color: '#F59E0B',
    icon: 'file-text',
    subcategories: [
      'Fee payment or refund issues',
      'Bonafide / certificate requests',
      'ID card or document correction',
      'Department coordination issues',
      'Late form submissions',
      'Internship or training approvals',
    ],
  },
  {
    id: 'discipline',
    name: 'Discipline & Harassment',
    color: '#DC2626',
    icon: 'alert-triangle',
    subcategories: [
      'Ragging complaints',
      'Sexual harassment (ICC cases)',
      'Student–student harassment',
      'Faculty / staff harassment',
      'Bullying / mental harassment',
      'Threats / intimidation',
      'Disciplinary action appeal',
    ],
  },
  {
    id: 'health',
    name: 'Health & Wellness',
    color: '#14B8A6',
    icon: 'heart',
    subcategories: [
      'Emergency medical response delay',
      'Mental health / counseling request',
      'Medical support',
    ],
  },
  {
    id: 'accessibility',
    name: 'Accessibility & Inclusion',
    color: '#8B5CF6',
    icon: 'users',
    subcategories: [
      'Ramp / lift not working',
      'Disability accommodation issues',
      'Special exam accommodation',
      'Assistive device support',
    ],
  },
  {
    id: 'technical',
    name: 'Technical',
    color: '#6366F1',
    icon: 'cpu',
    subcategories: [
      'Website / portal login issues',
      'Server downtime / form not loading',
      'Email or Wi-Fi not working',
      'College ERP or attendance portal bugs',
      'Lab system malfunction',
      'Network connectivity issues',
    ],
  },
  {
    id: 'infrastructure',
    name: 'Infrastructure',
    color: '#78716C',
    icon: 'grid',
    subcategories: [
      'Classroom furniture damaged',
      'Projector / smart board not working',
      'Lab equipment shortage',
      'Power backup failure',
      'Drinking water facility issues',
      'Building / fire safety concerns',
    ],
  },
  {
    id: 'hostel',
    name: 'Hostel',
    color: '#06B6D4',
    icon: 'home',
    subcategories: [
      'Room allocation or change request',
      'Water or electricity issue',
      'Mess food quality or timing',
      'Warden / staff behavior',
      'Cleanliness or maintenance delay',
      'Security / curfew concerns',
    ],
  },
  {
    id: 'library',
    name: 'Library',
    color: '#10B981',
    icon: 'book-open',
    subcategories: [
      'Book availability or delay in issue',
      'Library card problems',
      'Fine disputes',
      'System login issues',
      'Reading area maintenance',
    ],
  },
  {
    id: 'transport',
    name: 'Transport',
    color: '#F43F5E',
    icon: 'truck',
    subcategories: [
      'Bus timing / delay',
      'Route change request',
      'Driver / staff behavior',
      'Vehicle condition / seating issue',
      'Pass renewal or lost pass',
    ],
  },
  {
    id: 'canteen',
    name: 'Canteen / Food',
    color: '#EAB308',
    icon: 'coffee',
    subcategories: [
      'Food quality or hygiene issue',
      'Overpricing or billing error',
      'Menu variety / nutrition concern',
      'Staff misbehavior',
      'Waste management',
    ],
  },
  {
    id: 'placement',
    name: 'Placement & Career',
    color: '#7C3AED',
    icon: 'briefcase',
    subcategories: [
      'Placement eligibility disputes',
      'Company shortlisting complaints',
      'Internship stipend issues',
      'Training quality complaints',
      'Placement cell mismanagement',
      'Offer letter delay / mismatch',
    ],
  },
  {
    id: 'scholarship',
    name: 'Scholarship & External Portals',
    color: '#0891B2',
    icon: 'dollar-sign',
    subcategories: [
      'Govt / AICTE scholarship delay',
      'University portal issues',
      'Bank verification problems',
      'DBT amount not credited',
    ],
  },
  {
    id: 'research',
    name: 'Research / Projects',
    color: '#059669',
    icon: 'activity',
    subcategories: [
      'Guide allocation issues',
      'Project topic approval delay',
      'Lab access for research',
      'Research funding problems',
    ],
  },
  {
    id: 'security',
    name: 'Security',
    color: '#3B82F6',
    icon: 'shield',
    subcategories: [
      'Lost belongings',
      'Entry / exit disputes',
      'ID verification problems',
      'Misbehavior / harassment complaint',
      'Emergency response delay',
    ],
  },
  {
    id: 'cleanliness',
    name: 'Cleanliness / Maintenance',
    color: '#22C55E',
    icon: 'trash-2',
    subcategories: [
      'Washroom cleaning',
      'Classroom / corridor cleaning',
      'Garden or campus waste',
      'Equipment repair delay',
      'Pest control needed',
    ],
  },
  {
    id: 'others',
    name: 'Others',
    color: '#94A3B8',
    icon: 'tag',
    subcategories: [
      'Suggestions / improvements',
      'Event management complaints',
      'Student club / fest issues',
      'Power cut or water outage',
      'Other unspecified concern',
    ],
  },
];
